language: android
sudo: required
jdk: oraclejdk8

# safelist
#branches:
#  only:
#  - master
#  - develop

android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  # - tools
  # - platform-tools

  env:
    global:
      -ANDROID_API = 26
      -ANDROID_BUILD_TOOLS = 26.1.0
      -ADB_INSTALL_TIMEOUT=5 # minutes

  # The BuildTools version used by your project
  - build-tools-$ANDROID_BUILD_TOOLS

  # The SDK version used to compile your project
  - android-$ANDROID_API

  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

 

  before_install:
  - chmod +x gradlew

  script:
  - ./gradlew build